spring:
  application:
    name: ABCProductService
  profiles: CLOUD
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: default
    serviceUrl:
       defaultZone: http://localhost:3000/eureka
  instance:
    preferIpAddress: false
---